makaryb part4
ok-technopolis-autumn-2019/Makary_Boriskin pull request #3
Opened 2019-10-31 14:05 UTC by makaryb

Добавил работу stylelint, sass, postcss, parcel.
Подскажите - по бэму все норм? Возможно, все-таки некоторые моменты недопонял

2019-11-04 13:13 UTC, fromanywhere requested changes

2019-11-04 13:13 UTC, fromanywhere commented on .cache/6a/e83d09a1625e29bc08c7c48f7c2d56.json
> +{"id":"icons/completed.svg","dependencies":[{"name":"/home/makary2rtc/Documents/otherStudWork/Makary_Boriskin/package.json","includedInParent":true,"mtime":1572520192744}],"generated":{"js":"module.e
Ясно, что .cache нужно было заигнорить

2019-11-04 13:13 UTC, fromanywhere commented on build/postcss_style.css
> +html, body, div, h1, h2 input {
build обычно тоже игнорят

2019-11-04 13:13 UTC, fromanywhere commented on dist/close.1a8adba6.svg
> +<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
и dist обычно тоже игнорят!

2019-11-04 13:13 UTC, fromanywhere commented on index.html
> +		<link rel="stylesheet" href="build/postcss_style.css"/>
вообще странно, оно должно отлично работать, когда на исходник указывает

2019-11-04 13:13 UTC, fromanywhere commented on output.css
> +html, body, div, h1, h2 input {
короче в ревью должны только исходники попадать

2019-11-04 13:13 UTC, fromanywhere commented on postcss.config.js
> +		"autoprefixer": {}
Так а это, ну вот результат работы автопрефиксера я допустим вижу, это ок. Но не переменных, ни миксинов не вижу, а надо

2019-11-04 13:22 UTC, fromanywhere commented on build/postcss_style.css
> +.todo-toolbar__filters__clear-completed {
Это не по бэму, не может быть в селекторе два раза по __

2019-11-07 17:07 UTC, fromanywhere requested changes
Так а использования-то миксинов и переменных где?

2019-11-07 17:07 UTC, fromanywhere commented on package.json
> +{
Даже гитхаб говорит, что json невалиден. Попробуйте перед коммитом npm i сделать

2019-11-08 11:28 UTC, makaryb commented on package.json
> +{
Переделаю все заново правильно в новой ветке

2019-11-08 11:28 UTC, makaryb commented
Переделаю все заново правильно в новой ветке

2019-11-08 11:28 UTC, closed without merging